### ISSUE TITLE
Verify connection of OAuth App to Netlify

### ISSUE THREAD

**Issue by r-l-d** [deven-org/telemetry-functions#15]
## Description

In order to verify the connection of the OAuth app to netlify, we first need to confirm that the OAuth app has been invited to a repo. Then, the Github access token must be added to netlify as an environment variable. In addition, the webhook for the netlify endpoint has to be added to the repo org. 

## Acceptance Criteria

- [x] **Given that** the OAuth App is added to a repo
**when** a trackable event occurs in GitHub repo
**then** the App sends the event information to Netlify through the Webhook

## Technical Approach
 - Add the OAuth app to a repo (as a repo owner)
 - Get Github Access Token and add it to netlify
 - Add Webhook URL from netlify to the Github Repo webhook list.

**Comment by simon-novak** [comment]
Tshirt size: S
