### ISSUE TITLE
Define and track what will be shown in the MVP Demo

### ISSUE THREAD

**Issue by r-l-d** [deven-org/telemetry-functions#16]
## Goal of demo 

- Display a JSON file that is compiled from raw data collected automatically from Github when defined events occur. 
- Live demo will include slides explaining background of the telemetry project and DEVEN. 

## Process to show:
- [ ] How to invite an OAuth app to an org
- [ ] How to add a Webhook
- [ ] How Netlify "catches" the GitHub events
- [ ] How we store raw data on GitHub
- [ ] How we collect metrics from raw data

## Metrics to show:
- [ ] Does repo have deven-documentation skeleton?
- [ ] Commits per PR
- [ ] Files changed per PR
- [ ] Release version (SemVer info)
- [ ] Time from PR to merge
- [ ] Code review involvements (comments, reviewers invited)

## How to show it
- [ ] Quick introduction (slides)
- [ ] Live demo (OAuth App)
- [ ] Live demo (Netlify)
- [ ] Live demo (raw data and metrics)
- [ ] Conclusions (slides)

## Acceptance criterie
The goal, the process, the metrics of the demo are defined.

**Comment by simon-novak** [comment]
Tshirt size: Small

**Comment by Jumace** [comment]
New task is setup to create a presentation about current state of development
