### ISSUE TITLE
Metric: DEVEN tooling usage, e.g. documentation skeleton

### ISSUE THREAD

**Issue by r-l-d** [deven-org/telemetry-functions#17]
## Decription:
As a DEVEN team member, I want to understand whether the documentation is being used in a project and what files are being used. 

## Technical approach:
Use CronJob to check if deven-documentation-skeleton is in the dev dependencies in package.json

## Acceptance criteria:
- [x] Boolean whether or not deven-documentation-skeleton is used
- [x] List of what chapters are used (are all 8 files included?)

**Comment by simon-novak** [comment]
@r-l-d Please add technical approach.

**Comment by simon-novak** [comment]
Tshirt size: Small
