### ISSUE TITLE
Metric:     Builds (failed, succeeded, duration, tooling, script steps, software)

### ISSUE THREAD

**Issue by r-l-d** [deven-org/telemetry-functions#18]
## Description
Collect the metrics of builds
- Builds which are succeeded
- Builds which are failed
- Time taken for the completion of the builds
- Libraries and packages installed as dependencies for the builds

## Technical approach
- Setup(Cronjob or Event driven) to collect the emitted events or logs from the CI build system of the repo
- Collect the data through the server less function
- Transform into a desired format and store the data in the data repo

## Acceptance Criteria
- [x] Succeded / Not succeded
- [x] Duration
- [x] Packages as dependencies
- [x] Steps: succeded / not succeded
- [x] Steps: duration
- [x] Steps: name
- [x] Include a list of installed packages in the repository separated by dev dependencies and dependencies. 

## Questions
- [x] Is there a better way to identify the build scripts?
- [x] What does tooling refer to?
- [x] What does software refer to?

**Comment by simon-novak** [comment]
@pixari Please add the description and the technical approach.

**Comment by simon-novak** [comment]
Tshirt size: Medium

**Comment by simon-novak** [comment]
@pixari Please update the AC's.
