### ISSUE TITLE
Feat: add documentation to telemetry-functions

### ISSUE THREAD

**Issue by pixari** [deven-org/telemetry-functions#2]
## Acceptance Criteria

- [x] Install documentation-skeleton in the repo
- [x] Install the documentation files using the CLI
- [ ] Add documentation

### Document the following topics:

- [ ] How to run it
- [ ] How to install it
- [ ] How to test it
- [x] Add general purposes
- [x] How to contribute
- [ ] Next steps
- [x] Code of conduct
- [x] Architecture
- [x] Overall Structure
- [x] Technical decisions
- [x] Functional diagram

**Comment by r-l-d** [comment]
Include deven documentation-skeleton
