### ISSUE TITLE
Metric:     Amount of commits per PR (squash issue?) + amount of lines of code -/+

### ISSUE THREAD

**Issue by r-l-d** [deven-org/telemetry-functions#23]
## Description
Collect the metrics of amount of commits per PR, the amount of lines of code added and deleted along with the timestamp of commits

## Technical approach
- Configure Event driven architecture(Github Action) to collect data about the pull request.
- Collect the data through the server less function
- Transform into a desired format and store the data in the data repo

# Acceptance Criteria
- [x] Count of number of commits per PR
- [x] Number of lines added to code per PR
- [x]  Number of lines removed from code per PR
- [x] Time stamp of commits

**Comment by simon-novak** [comment]
@r-l-d Please add the description and the technical approach.

**Comment by simon-novak** [comment]
Tshirt size: M
