### ISSUE TITLE
Metric:     Code review involvements (PRs per repo, comments, duration of open PRs)

### ISSUE THREAD

**Issue by r-l-d** [deven-org/telemetry-functions#24]
## Description
Collect the metrics of code review involvements of a repository

## Technical approach
- Setup(Cronjob or Event driven) to collect the emitted events or logs of code review involvements
- Collect the data through the server less function
- Transform into a desired format and store the data in the data repo

## Acceptance Criteria

- [x] Number of PRs per repo
- [x] Comments per PR
- [x] Number of files changed per PR
- [x] Did the creator also merge the request? 
- [x] Number of invited reviewers
- [x] Duration of PRs – from opening a PR to merging a PR; from opening to accepting; from opening to updating. 

Related to: https://github.com/deven-org/telemetry-functions/issues/35

**Comment by simon-novak** [comment]
@r-l-d Please add the description and the technical approach.

**Comment by simon-novak** [comment]
Tshirt size: Medium
