### ISSUE TITLE
Metrics: Deployments on environments (env, duration, version, frequency)

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/telemetry-functions#35]
## Description
Collect the metrics of Deployments of environments
- To which environment
- Amount of Time to complete the deployment
- Version of the deployments
- Frequency of deployment in a specific environment 

## Technical approach
- Setup(Cronjob or Event driven) to collect the emitted events or logs from the CI build system of the repo
- Collect the data through the server less function
- Transform into a desired format and store the data in the data repo

## Acceptance criteria 
Metrics measuring deployments on environments are tracked and the data is stored in the data repo. 

Blocked by: https://github.com/deven-org/telemetry-functions/issues/24

**Comment by simon-novak** [comment]
@mdsign Please add details.

**Comment by simon-novak** [comment]
Tshirt size: M

**Comment by Jumace** [comment]
done
