### ISSUE TITLE
Create detailed list of Step 1 Metrics

### ISSUE THREAD

**Issue by simondoingtingz** [deven-org/telemetry-functions#38]
## Description:
A detailed list of all Step 1 metrics, broken down by sub-metric. Include metric type and availability in the version control system (Github, Gitlab, Bitbucket) API

## ACs:
 - [ ] A list of all Step 1 metrics and sub metrics is created
 - [ ] Metric type is included as an attribute
 - [ ] Availability in the Github, Bitbucket, and Gitlab API is included

## Technical Approach:
This task requires a deep analysis of each metric to determine the following: 
1. What information is this metric trying to collect?
2. How many sub-metrics are in this metric?
3. What are the data types of all metrics and sub-metrics?
4. Are each of these sub-metrics and metrics available as data through the Github API? Gitlab API? BitBucket API?

**Comment by r-l-d** [comment]
Metric List: https://docs.google.com/spreadsheets/d/11ufRxU0DLUj44KPRWCyp3OM5Jib02WOQG5ynM0FAeqw/edit?usp=sharing

**Comment by Jumace** [comment]
Done, list of metrics is now part of documentation
