### ISSUE TITLE
doc: add API documentation

### ISSUE THREAD

**Issue by pixari** [deven-org/telemetry-functions#42]
## ACs:
 - [x] Define the list of events
 - [x] (event doc): payload (link to github, example, schema, ...)
 - [x] Define the list of metrics
 - [x] (metric doc): event used, output
 - [x] Add a Postman request for each event
 - [x] Update the postman collection

This ticket is related to #78.

**Comment by simon-novak** [comment]
@pixari Please add a technical approach. Thanks!

**Comment by mdsign** [comment]
In the documentation 
- Webhook Events are added with description and GitHub links
- Collected metrics also listed with event used and output

Pending Task:
- Add a Postman request for each event which needs Netlify login credentials
- Update the postman collection

**Comment by Jumace** [comment]
done
