### ISSUE TITLE
doc: improve the overall documentation

### ISSUE THREAD

**Issue by pixari** [deven-org/telemetry-functions#78]
## Description:

- Our team has achieved rapid feature development.
- Although we have produced some overarching documentation, there is room for enhancement by refining its specificity and comprehensiveness.
- This presents an excellent occasion to conduct a thorough examination of the application's architecture.

## ACs:
 - [x] #79
 - [x] #80 
 - [x] #81  
 - [x] #82 
 - [x] #83
 - [x] #42 

 
## Technical Approach:

- Our primary objective is to facilitate the seamless integration of new developers into our project, without requiring prior knowledge or familiarity with the telemetry-functions. Specifically, this involves empowering them to expand the collection of the  new metrics.

- During the analysis of the application, please do not hesitate to document any potential enhancements or improvements that come to mind.

**Comment by Jumace** [comment]
done
