### ISSUE TITLE
doc: add terms to Glossary

### ISSUE THREAD

**Issue by pixari** [deven-org/telemetry-functions#79]
## Description:
The utilization of project-specific terminologies can pose a significant obstacle to new members joining the team. Therefore, to mitigate this issue, we must provide a comprehensive list of terms and their definitions to eliminate any potential gatekeeping.

## ACs:
 - [x] Define a list of terms
 - [x] Add the terms/description to the table
 
## Technical Approach:
The location of the **glossary page** can be accessed via the following path: ./doc/GLOSSARY.md
In the event that supplementary pages are required, kindly ensure to include links to them within the main page.

### Related tickets:

1. #78

**Comment by Jumace** [comment]
implemented
