### ISSUE TITLE
doc: add ProjectBackground

### ISSUE THREAD

**Issue by pixari** [deven-org/telemetry-functions#80]
## Description:

Our primary objective is to facilitate the seamless integration of new developers into our project, without requiring prior knowledge or familiarity with the telemetry-functions. Specifically, this involves empowering them to expand the collection of the new metrics.

## ACs:
 - [x] Add the project background
 

## Technical Approach:
The location of the **project background** can be accessed via the following path: ./doc/PROJECTBACKGROUND.md
In the event that supplementary pages are required, kindly ensure to include links to them within the main page.

### Related tickets:

1. #78

**Comment by Jumace** [comment]
implemented
