### ISSUE TITLE
doc: add Testing

### ISSUE THREAD

**Issue by pixari** [deven-org/telemetry-functions#81]
## Description:
A "Testing" page has been added to the documentation using DocumentationSkeleton.  
It is still empty.

## ACs:
 - [ ] Add "how to run tests"
 - [ ] Few words about our testing strategy (why do we write test? What's our goal?)
 - [ ] Mention the minimum test coverage and how we'd like to enforce it
 - [ ] Few words about test driven development

## Technical Approach:
The location of the **testing page** can be accessed via the following path: ./doc/TESTING.md
In the event that supplementary pages are required, kindly ensure to include links to them within the main page.

### Related tickets:

1. #78

**Comment by mdsign** [comment]
Review comments are fixed and pushed

**Comment by Jumace** [comment]
implemented
