### ISSUE TITLE
doc: add Deployment

### ISSUE THREAD

**Issue by pixari** [deven-org/telemetry-functions#82]
## Description:
A "Deployment" page has been added to the documentation using DocumentationSkeleton.  
It is still empty.

## ACs:
 - [x] We create releases on Github (https://github.com/deven-org/telemetry-functions/releases)
 - [x] We publish the package on Github (https://github.com/orgs/deven-org/packages?repo_name=telemetry-functions)
 - [x] We use a workflow on our CI/CD to create releases based on the GitHubAction "release-please". (https://github.com/deven-org/telemetry-functions/blob/main/.github/workflows/release.yml)
 - [x] Few words about release-please
 - [x] How does it work the deployment on Netlify?
 

## Technical Approach:
The location of the "Deployment page" can be accessed via the following path: ./doc/DEPLOYMENT.md
In the event that supplementary pages are required, kindly ensure to include links to them within the main page.

### Related tickets:

1. https://github.com/deven-org/telemetry-functions/issues/78

**Comment by r-l-d** [comment]
PR here: https://github.com/deven-org/telemetry-functions/pull/89

**Comment by Jumace** [comment]
implemented
