### ISSUE TITLE
doc: improve Contribute

### ISSUE THREAD

**Issue by pixari** [deven-org/telemetry-functions#83]
## Description:
Every developer should be able to contribute to the project after reading the "contribute" page.

## ACs:
 - [x] Please ensure to document the folder structure comprehensively
 - [x] Additionally, include a GIF format diagram for better visualization and understanding of the system's components.
 - [x] Describe the diagram in detail and provide a clear definition of what a "DataEvent" is
 - [x] Explain the function of a "DataEventSignature" and a "MetricSignature" and clarify whether a metric can belong to multiple events
 - [x] Provide insight into why adding a data event signature and a metric signature is necessary and explain how to add metric conditions
 - [x] Describe the "core" functions and provide a template for metrics that can be easily replicated
 - [x] It would be helpful to provide guidelines on how to write tests and why filtering the output is essential
 - [x] Explain the role of the "storeData" function and identify where environment variables are stored
 - [x] Mention the use of Postman
 - [x] Explain the use of the OAuth App. 

## Technical Approach:
The location of the "**contribute page**" can be accessed via the following path: ./doc/CONTRIBUTE.md
In the event that supplementary pages are required, kindly ensure to include links to them within the main page.

### Related tickets:
1. https://github.com/deven-org/telemetry-functions/issues/78

**Comment by Jumace** [comment]
parts are implemented, other parts are obsolete
