### ISSUE TITLE
Metrics: add signature for custom events

### ISSUE THREAD

**Issue by r-l-d** [deven-org/telemetry-functions#87]
**Description:** Currently there is no way to sign custom events in telemetry-functions. 

**ACs:**
- [ ] All custom events are signed automatically 

**Technical Approach:**
Another header property should be defined for custom events, like "X-Deven-Event" in order to signify that a custom event has occurred.

**Comment by Jumace** [comment]
implemented by now:
https://github.com/deven-org/telemetry-functions/blob/main/netlify/functions/metrics.ts
