### ISSUE TITLE
Exclude dependabot PRs from all PR metrics

### ISSUE THREAD

**Issue by r-l-d** [deven-org/telemetry-functions#90]
### Description: 
All PR metrics should exclude PRs that were created by dependabot. These PRs will create misleading data sets as they are not representative of developer work.

### ACs: 
- [ ] All PR metrics exclude PRs created by dependabot

### Technical Approach:
Get PR creator name (dependabot) from PR event payload, and filter PRs based on that name.

**Comment by Jumace** [comment]
Closed as after a through discussion it was agreed that Dependabot PRs should be included.
Those PRs are part of the development process, which we want to track. And those PRs often still involve some human interaction and time effort.
